import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Breadcrumb, ConfigProvider, Layout, Typography } from "antd";
import { Footer, Content } from "antd/es/layout/layout";
import PortfolioHeader from "@/components/PortfolioHeader";
import Portfolio from "@/components/tai-ye-en-portfolio";

const { Title, Paragraph, Text, Link } = Typography;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider>
            <Layout style={{ minHeight: "100vh" }}>
              <Portfolio />
              {/* <PortfolioHeader />
              <Content style={{ padding: "0 48px" }}>
                <Breadcrumb
                  style={{ margin: "16px 0" }}
                  items={[
                    { title: "Home" },
                    { title: "List" },
                    { title: "App" },
                  ]}
                />
                <div
                  style={{
                    // background: colorBgContainer,
                    minHeight: 280,
                    padding: 24,
                    // borderRadius: borderRadiusLG,
                  }}
                >
                  Content
                  {children}
                </div>
              </Content>
              <Footer style={{ textAlign: "center" }}>
                Ant Design ©{new Date().getFullYear()} Created by Ant UED
              </Footer> */}
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
